# Generated by Django 2.1.5 on 2019-03-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area_hectares',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.CharField(max_length=128),
        ),
    ]
